# Generated by Django 5.0.4 on 2024-04-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_todo_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="tasks",
                to="app_todo_list.tag",
            ),
        ),
    ]
